name: Bug report
description: Report a reproducible bug in fnvision.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        Please provide enough detail so we can reproduce and fix it quickly.

  - type: input
    id: version
    attributes:
      label: fnvision version
      description: Example: 0.1.0, main, or commit SHA
      placeholder: 0.1.0
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.11.9"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows
        - Linux
        - macOS
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Bug summary
      description: What happened, and what did you expect instead?
      placeholder: Clear summary of the problem.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide minimal, ordered steps.
      placeholder: |
        1. Run ...
        2. Call ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: minimal_code
    attributes:
      label: Minimal code sample
      description: Paste the smallest snippet that reproduces the bug.
      render: python
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error output / traceback
      description: Paste the full error output if available.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Screenshots, environment details, related links.
    validations:
      required: false
